from enum import Enum


class Permission(str, Enum):

    BUSINESS_CREATE = "BUSINESS_CREATE"
    BUSINESS_READ = "BUSINESS_READ"
    BUSINESS_UPDATE = "BUSINESS_UPDATE"
    BUSINESS_DELETE = "BUSINESS_DELETE"

    MEMBERSHIP_READ = "MEMBERSHIP_READ"
    MEMBERSHIP_CREATE = "MEMBERSHIP_CREATE"
    MEMBERSHIP_UPDATE = "MEMBERSHIP_UPDATE"
    MEMBERSHIP_DELETE = "MEMBERSHIP_DELETE"

    INVITATION_CREATE = "INVITATION_CREATE"
    INVITATION_READ = "INVITATION_READ"
    INVITATION_ACCEPT = "INVITATION_ACCEPT"
    INVITATION_DELETE = "INVITATION_DELETE"

    USER_READ = "USER_READ"
    USER_UPDATE = "USER_UPDATE"

    AI_AGENT_MANAGE = "AI_AGENT_MANAGE"
    CRM_MANAGE = "CRM_MANAGE"
    BILLING_MANAGE = "BILLING_MANAGE"