from enum import Enum

class NotificationType(str, Enum):
    APPOINTMENT_CREATED = "APPOINTMENT_CREATED"
    APPOINTMENT_CANCELLED = "APPOINTMENT_CANCELLED"
    APPOINTMENT_COMPLETED = "APPOINTMENT_COMPLETED"
    DOCUMENT_READY = "DOCUMENT_READY"
    DOCUMENT_FAILED = "DOCUMENT_FAILED"
    INVOICE_CREATED = "INVOICE_CREATED"
    INVOICE_PAID = "INVOICE_PAID"
    TEAM_INVITATION = "TEAM_INVITATION"
    SYSTEM = "SYSTEM"
