services:

  postgres:
    image: pgvector/pgvector:pg18
    container_name: businessos-postgres

    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: businessos_ai

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql


volumes:
  postgres_data: