"""add embedding vector to document chunks

Revision ID: 8c9f4d902fea
Revises: a4f3731fa71a
Create Date: 2026-07-21 13:42:34.282149

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8c9f4d902fea'
down_revision: Union[str, Sequence[str], None] = 'a4f3731fa71a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
